version: '3.4'

services:
  grafana:
    depends_on:
      - influxdb
    networks:
      - public
    image: grafana/grafana
    ports:
      - 3000:3000
    configs:
      - source: grafana-datasource
        target: /etc/grafana/provisioning/datasources/datasource.yaml
    deploy:
      placement:
        constraints:
          - "node.labels.nodeType==monitoring"
configs:
  grafana-datasource:
    file: ./grafana/provisioning/datasources/datasource.yaml

networks:
  public:
    external:
      name: public
